runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  SECRET_KEY: "your-secret-key"
  GOOGLE_CLIENT_ID: "your-google-client-id"
  GOOGLE_CLIENT_SECRET: "your-google-client-secret"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
